In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])
print(np.sum(arr))

21


In [9]:
np.mean(arr)

np.float64(3.5)

In [6]:
np.median(arr)

np.float64(3.5)

In [10]:
np.std(arr) # here std -> how spead our data is 

np.float64(1.707825127659933)

In [11]:
np.var(arr)

np.float64(2.9166666666666665)

In [12]:
np.min(arr)

np.int64(1)

In [13]:
np.max(arr)

np.int64(6)

In [14]:
matrix = np.array([[1,2,4],
                   [4,5,6],
                   [7,8,9]])
np.sum(matrix, axis =0)

array([12, 15, 19])

In [15]:
np.sum(matrix, axis =1)

array([ 7, 15, 24])

In [16]:
# Comulative Operations -> running total
arr 

array([1, 2, 3, 4, 5, 6])

In [17]:
print(np.cumsum(arr))

[ 1  3  6 10 15 21]


In [18]:
print(np.cumprod(arr))

[  1   2   6  24 120 720]
