In [5]:
import numpy as np
# Reshape
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
reshaped = arr.reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
reshaped2 = reshaped.reshape(2,3)
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [12]:
# ravel -> convert to 1D array
# it returns a view
ravel = reshaped2.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [13]:
# flatten -> also convert to 1D array
# return a copy of an array 
flat = reshaped2.flatten()
flat

array([1, 2, 3, 4, 5, 6])

In [14]:
ravel[0] = 69
print(ravel)
print(reshaped2)

[69  2  3  4  5  6]
[[69  2  3]
 [ 4  5  6]]


In [15]:
print(reshaped2)

[[69  2  3]
 [ 4  5  6]]


In [16]:
print(flat)

[1 2 3 4 5 6]
