In [1]:
import numpy as np

In [3]:
array = np.array([1,2,3,4,5])
result = np.where(array <= 3,"low", "high")
result

array(['low', 'low', 'low', 'high', 'high'], dtype='<U4')

# argwhere -> row-column positions for 2d arrays

In [9]:
array = np.array([10,20,30,40,50,60])
print(np.argwhere(array >= 40))

[[3]
 [4]
 [5]]


In [11]:
mask = np.logical_and(array > 15, array >45)
mask

array([False, False, False, False,  True,  True])

In [12]:
# for 2d array

In [17]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(np.argwhere(matrix > 5))


[[1 2]
 [2 0]
 [2 1]
 [2 2]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# in py we use and & or but in numpy we use ligical_and & logical_or

In [26]:
# logical_and
arr = np.array([10,30,45,35,96,56])
mask = np.logical_and(arr > 15 , arr <96)
print(mask)
arr[mask]

[False  True  True  True False  True]


array([30, 45, 35, 56])

In [29]:
arr2 = np.array([10,30,45,35,96,56])
mask2 = np.logical_or(arr > 30 , arr <96)
print(mask2)
arr2[mask2]

[ True  True  True  True  True  True]


array([10, 30, 45, 35, 96, 56])

In [32]:
# no zero
arr = np.array([0,4,0,5,6,0,34,3,6,0])
non_zero = np.nonzero(arr)
print(non_zero)

(array([1, 3, 4, 6, 7, 8]),)
