In [4]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
lst = ["yash",1,2.4,2]
arr = np.array(lst)
arr

array(['yash', '1', '2.4', '2'], dtype='<U32')

In [9]:
array = np.array([2,3,4,5,])
array

array([2, 3, 4, 5])

In [10]:
array.dtype

dtype('int64')

In [11]:
array = np.array([2,3,4,5,], dtype = np.float64)
array

array([2., 3., 4., 5.])

In [12]:
array.dtype

dtype('float64')

In [14]:
array = np.array([2.5,3.14,4.54,5.2], dtype = np.int64 )
array

array([2, 3, 4, 5])

In [15]:
array.dtype

dtype('int64')

In [20]:
#typecasting 

In [16]:
arr = np.array([2,3,5,7,5])
arr

array([2, 3, 5, 7, 5])

In [18]:
new_arr = arr.astype(np.float64)
new_arr

array([2., 3., 5., 7., 5.])

In [19]:
new_arr.dtype

dtype('float64')

In [21]:
new_arr2 = new_arr.astype(np.int64)
new_arr2

array([2, 3, 5, 7, 5])

In [22]:
#Typecasting_errors

In [27]:
array = np.array(["2","Yash","4"])
array


array(['2', 'Yash', '4'], dtype='<U4')

In [28]:
new_array = array.astype(np.int64)
new_array

ValueError: invalid literal for int() with base 10: np.str_('Yash')

In [29]:
new_array2 = array.astype(np.float64)
new_array2

ValueError: could not convert string to float: np.str_('Yash')

In [30]:
# we cann't convert a String to INT or FLOAT

In [31]:
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
array.ndim # to check dimension of an array

2

In [35]:
array.shape # to check shape of an array

(2, 3)

In [36]:
array.size # to check size of an array

6

In [37]:
array.itemsize

8