In [1]:
import numpy as np

In [4]:
arr = np.array([[1,2,4],[5,6,8],[1,3,4]])
arr

array([[1, 2, 4],
       [5, 6, 8],
       [1, 3, 4]])

In [5]:
print(arr.transpose())

[[1 5 1]
 [2 6 3]
 [4 8 4]]


## Swapaxes -> swap 2 specific axes in a matrix

In [6]:
arr = np.array([[[1,3],[4,5]]])
arr.shape

(1, 2, 2)

In [9]:
swap = arr
swap.shape

(1, 2, 2)

In [17]:
arr = np.swapaxes(arr, 0,1)
swap.shape

(2, 1, 2)